ci:
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      # https://github.com/pre-commit/pre-commit-hooks/issues/718
      # - id: check-added-large-files  # Fails with git v1.8.3
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: (requirements.txt)$
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: "24.10.0"
    hooks:
      - id: black
      - id: black-jupyter

  - repo: https://github.com/PyCQA/flake8
    rev: "7.1.1"
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: "5.13.2"
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.2"
    hooks:
      - id: mypy
        additional_dependencies:
        - types-pkg_resources
        - types-python-dateutil
        - types-requests

  # - repo: https://github.com/PyCQA/pydocstyle
  #   rev: "6.3.0"
  #   hooks:
  #     - id: pydocstyle
  #       # https://github.com/PyCQA/pydocstyle/pull/608#issuecomment-1381168417
  #       additional_dependencies: ['.[toml]']
  #       exclude: tests
